import type { Sunum } from "@/components/SunumOnizleme";

/**
 * Kendi ilanlarıma gelen sunumlar (birden fazla talep).
 * Profil > Gelen Sunumlar listesi ile karşılaştırma sayfası aynı kaynaktan okur;
 * karşılaştırma her zaman TEK bir talep içinde yapılır.
 */
export const GELEN_TALEP_ID = "dawn-fm-imzali-cd";

export type GelenSunum = Sunum & {
  id: string;
  /** Sunumun gönderildiği talep — karşılaştırma yalnızca aynı talep içinde yapılır. */
  talepId: string;
  satici: string;
  harf: string;
  puan: string;
  saticiTipi: "Mağaza" | "Bireysel";
  /** Satıcının BulBana geçmişi — karşılaştırmada tartılır. */
  satis: number;
  yanitSaat: number;
  zamanindaKargo: number;
  ne: string;
};

export const gelenSunumlar: GelenSunum[] = [
  {
    id: "plakdukkani34",
    talepId: "dawn-fm-imzali-cd",
    satici: "plakdukkani34",
    harf: "PD",
    puan: "4.8",
    saticiTipi: "Mağaza",
    satis: 214,
    yanitSaat: 1,
    zamanindaKargo: 98,
    ne: "1 gün önce",
    baslik: "Jelatininde Avrupa baskısı Dawn FM · imza kartlı",
    fiyatNum: 4250,
    urun: "The Weeknd Dawn FM",
    muadil: false,
    yil: "2022",
    durum: "Kutusu açılmamış",
    defoVar: false,
    kutu: true,
    aksesuar: true,
    teslim: "Bugün kargoda",
    kargo: "Kargo satıcıya ait",
    il: "İstanbul",
    ilce: "Beyoğlu",
    aciklama:
      "Jelatininde Avrupa baskısı. İmza kartla birlikte, COA sertifikası mevcut.",
    fotolar: 5,
    video: true,
  },
  {
    id: "muzikmarket",
    talepId: "dawn-fm-imzali-cd",
    satici: "muzikmarket",
    harf: "MM",
    puan: "4.6",
    saticiTipi: "Mağaza",
    satis: 1204,
    yanitSaat: 2,
    zamanindaKargo: 96,
    ne: "2 gün önce",
    baslik: "Dawn FM CD — imzalı, sertifikalı",
    fiyatNum: 4500,
    urun: "The Weeknd Dawn FM",
    muadil: false,
    yil: "2022",
    durum: "Az kullanılmış",
    defoVar: false,
    kutu: true,
    fatura: true,
    teslim: "1–2 gün içinde kargoda",
    kargo: "Kargo alıcıya ait",
    il: "Ankara",
    ilce: "Çankaya",
    aciklama:
      "Mağaza stoğundan. Etkinlik imzası, kanıt fotoğraflı. Aynı gün kargo.",
    fotolar: 4,
  },
  {
    id: "koleksiyoner.mert",
    talepId: "dawn-fm-imzali-cd",
    satici: "koleksiyoner.mert",
    harf: "KM",
    puan: "4.9",
    saticiTipi: "Bireysel",
    satis: 58,
    yanitSaat: 5,
    zamanindaKargo: 91,
    ne: "Dün",
    baslik: "Dawn FM imzalı CD — kapakta hafif çizik",
    fiyatNum: 3900,
    urun: "The Weeknd Dawn FM",
    muadil: false,
    yil: "2021",
    durum: "Kullanılmış",
    defoVar: true,
    defoNot: "kapakta hafif çizik",
    kutu: true,
    teslim: "3 gün içinde kargoda",
    kargo: "Kargo satıcıya ait",
    il: "İzmir",
    ilce: "Karşıyaka",
    aciklama:
      "Kişisel koleksiyondan, kapakta imza. Kutuda ince çizik; kitapçık ve disk temiz.",
    fotolar: 3,
  },
  {
    id: "cdkolik",
    talepId: "dawn-fm-imzali-cd",
    satici: "cdkolik",
    harf: "CK",
    puan: "4.7",
    saticiTipi: "Bireysel",
    satis: 132,
    yanitSaat: 3,
    zamanindaKargo: 94,
    ne: "3 gün önce",
    baslik: "Dawn FM CD — imzalı, kutusunda",
    fiyatNum: 4400,
    urun: "The Weeknd Dawn FM",
    muadil: false,
    yil: "2022",
    durum: "Yenilenmiş",
    defoVar: false,
    kutu: true,
    fatura: true,
    aksesuar: true,
    teslim: "1–2 gün içinde kargoda",
    kargo: "Kargo satıcıya ait",
    il: "İstanbul",
    ilce: "Şişli",
    aciklama:
      "Kutusu ve faturasıyla birlikte. İmza fotoğrafta net görünüyor, jelatini açılmış.",
    fotolar: 6,
    video: true,
  },
  {
    id: "retrodukkan",
    talepId: "dawn-fm-imzali-cd",
    satici: "retrodukkan",
    harf: "RD",
    puan: "4.5",
    saticiTipi: "Mağaza",
    satis: 340,
    yanitSaat: 8,
    zamanindaKargo: 89,
    ne: "4 gün önce",
    baslik: "Dawn FM CD — muadil Avrupa baskısı",
    fiyatNum: 3600,
    urun: "The Weeknd Dawn FM (muadil baskı)",
    muadil: true,
    yil: "2023",
    durum: "Kutusu açılmamış",
    defoVar: false,
    kutu: true,
    teslim: "3 gün içinde kargoda",
    kargo: "Kargo alıcıya ait",
    il: "Bursa",
    ilce: "Nilüfer",
    aciklama:
      "İmzasız muadil baskı; jelatininde ve sıfır. Bütçeni zorlamak istemeyenler için.",
    fotolar: 3,
  },
  // ── Kraftwerk "The Man-Machine" plak talebine gelenler ──
  {
    id: "plakevi",
    talepId: "kraftwerk-man-machine-plak",
    satici: "plakevi",
    harf: "PE",
    puan: "4.7",
    saticiTipi: "Mağaza",
    satis: 410,
    yanitSaat: 2,
    zamanindaKargo: 95,
    ne: "2 gün önce",
    baslik: "The Man-Machine — 1978 Almanya baskısı",
    fiyatNum: 3100,
    urun: "Kraftwerk The Man-Machine",
    muadil: false,
    yil: "1978",
    durum: "Az kullanılmış",
    defoVar: false,
    kutu: true,
    teslim: "1–2 gün içinde kargoda",
    kargo: "Kargo satıcıya ait",
    il: "İstanbul",
    ilce: "Kadıköy",
    aciklama:
      "Orijinal iç zarfıyla. Kapak keskin, plak çizik barındırmıyor; test edildi.",
    fotolar: 5,
    video: true,
  },
  {
    id: "vinylci.baris",
    talepId: "kraftwerk-man-machine-plak",
    satici: "vinylci.baris",
    harf: "VB",
    puan: "4.4",
    saticiTipi: "Bireysel",
    satis: 41,
    yanitSaat: 6,
    zamanindaKargo: 88,
    ne: "Dün",
    baslik: "The Man-Machine plak — kapakta hafif yıpranma",
    fiyatNum: 2650,
    urun: "Kraftwerk The Man-Machine",
    muadil: false,
    yil: "1981",
    durum: "Kullanılmış",
    defoVar: true,
    defoNot: "kapak köşelerinde yıpranma",
    teslim: "3 gün içinde kargoda",
    kargo: "Kargo alıcıya ait",
    il: "İzmir",
    ilce: "Bornova",
    aciklama:
      "Kişisel koleksiyondan; plak temiz, kapak köşeleri yıpranmış. Fiyat buna göre.",
    fotolar: 3,
  },
  // ── "Tutunamayanlar" ilk baskı talebine gelenler ──
  {
    id: "sahafmehmet",
    talepId: "tutunamayanlar-ilk-baski",
    satici: "sahafmehmet",
    harf: "SM",
    puan: "4.9",
    saticiTipi: "Mağaza",
    satis: 620,
    yanitSaat: 1,
    zamanindaKargo: 97,
    ne: "3 gün önce",
    baslik: "Tutunamayanlar 1. baskı — 1972, ciltli",
    fiyatNum: 7200,
    urun: "Oğuz Atay Tutunamayanlar (1. baskı)",
    muadil: false,
    yil: "1972",
    durum: "Az kullanılmış",
    defoVar: false,
    teslim: "Bugün kargoda",
    kargo: "Kargo satıcıya ait",
    il: "İstanbul",
    ilce: "Beyoğlu",
    aciklama:
      "Sayfalar tam ve temiz, sararma minimum. Cildi orijinal, sırt sağlam.",
    fotolar: 6,
    video: true,
  },
];
